# For the moment for test I use master and not release
# Author: Stéphane Bressani
# Deploy on azure
# For the future -> cargo test --all (build --all ???)
trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: CmdLine@2
    inputs: 
      script:
        rm -rf ./.env
    displayName: Remove env file (if exist)
  - task: CmdLine@2
    inputs:
      script: |
        echo 'DATABASE_URL=postgres://$(pg-login):$(pg-password)@$(pg-ip)/partages_web
        ROCKET_ADDRESS=localhost
        ROCKER_PORT=8001' >> ./.env
    displayName: Config db
  - task: CmdLine@2
    inputs:
      script: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
    displayName: Install rust
  - task: CmdLine@2
    inputs:
      script: rustup toolchain install nigthly
    displayName: Install rust nigthly
  - task: CmdLine@2
    inputs:
      script: rustup default nigthly
    displayName: Switch to rust nigthly
  - task: CmdLine@2
    inputs:
      script: cargo install cargo-web
    displayName: Install cargo-web
  - task: CmdLine@2
    inputs:
      script: cargo build --release
    displayName: Compile
  - task: CmdLine@2
    inputs:
      script: rm -rf target-final
    displayName: Create a final repertory
  - task: CmdLine@2
    inputs:
      script: mv ./.env ./target-final
    displayName: Move config
  - task: CmdLine@2
    inputs:
      script: mv ./public/ ./target-final/public/
    displayName: Move static html backend
  - task: CmdLine@2
    inputs:
      script: mv ./target/release/paratages_web ./target-final/serve
    displayName: Move binary
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/target-final'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/partages_web.zip'
      replaceExistingArchive: true
      verbose: # (no value); this input is optional
  - task: FtpUpload@2
    inputs:
      credentialsOption: 'inputs'
      serverUrl: 'ftp://$(ftp-ip)'
      username: '$(ftp-user)'
      password: '$(ftp-password)'
      rootDirectory: '$(Build.ArtifactStagingDirectory)'
      filePatterns: '**'
      remoteDirectory: '/home/stephane/ftp/build/$(Build.BuildId)/'
      clean: false
      cleanContents: false
      preservePaths: false
      trustSSL: false
